version: "3"
tasks:
  sql-lint:
    cmds:
      - poetry run sqlfluff lint transform/wcl_dbt/models/
  sql-fix:
    cmds:
      - poetry run sqlfluff fix transform/wcl_dbt/models/
  dbt-run:
    dir: ./transform/wcl_dbt/
    cmds:
      - poetry run dbt run
  dbt-run-fr:
    dir: ./transform/wcl_dbt/
    cmds:
      - poetry run dbt run --full-refresh
  dbt-docs:
    deps: [dbt-run]
    dir: ./transform/wcl_dbt/
    cmds:
      - poetry run dbt docs generate
      - poetry run dbt docs serve
  dbt-test:
    dir: ./transform/wcl_dbt/
    cmds:
      - poetry run dbt test
  db-up:
    dir: ./db
    cmds:
      - docker compose up
  db-down:
    dir: ./db
    cmds:
      - docker compose down
  db-insert:
    dir: ./db/scripts
    cmds:
      - poetry run python create_db_insert_data.py
